language: php

php:
  - 8.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/psalm --no-progress
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php ./vendor/bin/php-coveralls

services:
  - mysql

sudo: false
